version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.0.0
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  verify-deployment:
    executor: aws-cli/default
    docker:
      - image: 'node:13.12.0-alpine'
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition "counter-app-task" \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            $BASH_ENV
      - aws-ecs/update-task-definition-from-json:
          task-definition-json: counter-app-definition.json 
      - aws-ecs/verify-revision-is-deployed:
          family: 'counter-app-service'
          cluster: 'couner-app-cluster'
          task-definition-arn: '${TASK_DEFINITION_ARN}'

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "counter-app-ecr-repo"
          tag: "latest"
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: 'counter-app-service'
          cluster: 'couner-app-cluster'
          container-image-name-updates: 'container=counter-app-service,tag=latest'

test-workflow:
    jobs:
      - verify-deployment
